### PR TITLE
Fix Travis builds for Mistral

### LINKED ISSUE #1925: Update Mistral script for Travis
https://github.com/StackStorm/st2/blob/master/scripts/travis/setup-mistral.sh needs updating with recent changes.

Because of that it fails Mistral tests in Travis.

Additional notes from @m4dcoder 

> if the commit is on st2 master, then the MISTRAL_STABLE_BRANCH should be master.  otherwise, should match the st2 version number (i.e. st2-0.13.1)

### PR DESCRIPTION
**Pull request by armab**
* Synchronize Mistral Installation script for Travis with recent `st2_deploy` changes.
* PR for st2 [`master`](https://github.com/StackStorm/st2/tree/master) branch now should use  `MISTRAL_STABLE_BRANCH="master"`
* Otherwise use `MISTRAL_STABLE_BRANCH="st2-0.13.0"`

Fixes #1925

### CODE REVIEW

File: scripts/travis/setup-mistral.sh [hunk 1]
```diff
@@ -6,8 +6,39 @@ if [ "$(whoami)" != 'root' ]; then
     exit 2
 fi
 
-MISTRAL_STABLE_BRANCH="st2-0.9.0"
+function version_ge() { test "$(echo "$@" | tr " " "\n" | sort -V | tail -n 1)" == "$1"; }
+
+# Determine which mistral version to use
+if [[ "${TRAVIS_BRANCH}" == 'master' ]]; then
```
Comment (Kami) [inline scripts/travis/setup-mistral.sh]: This is and will be a pain to maintain in sync with st2_deploy :/

Comment (armab) [inline scripts/travis/setup-mistral.sh]: What can I do here?

Refactor `st2_deploy.sh` to re-use ssh functions as mentioned in https://github.com/StackStorm/st2/pull/1778#issue-98418711 ?

If so, isn't `st2_deploy.sh` to be deprecated soon?

Comment (armab) [inline scripts/travis/setup-mistral.sh]: I think it's good that we made `mistral` builds optional. So they have just optional informational purpose.

Comment (Kami) [inline scripts/travis/setup-mistral.sh]: Realistically speaking - there is not much we can do right now.

Ideally, we could make parts of st2_deploy.sh more re-usable (so we could re-use parts we need here), but I don't think we want to do this right now.

**Comment by Kami** [comment]
Tests pass so I'm going to merge this for now.

Eventually, we should come up with a better and more maintainable plan.

**Comment by armab** [comment]
Yeah, I'm for having at least some information/feedback from such "open for everyone" CI tests, instead of having nothing.
Especially useful for OSS when someone creates PR.

**Comment by Kami** [comment]
Merged, thanks.
